[project]
name = "encodingandembedding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vishal Yadav", email = "vishalemail01@gmail.com" }
]
requires-python = "==3.11.*"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "datasets>=2.19.0",
    "docling>=2.121.0",
    "docx2txt>=0.9",
    "gensim==4.3.2",
    "ipykernel>=7.3.0",
    "jq>=1.12.0",
    "langchain>=1.3.16",
    "langchain-anthropic>=1.6.1",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-docling>=3.0.0",
    "langchain-google-genai>=4.3.5",
    "langchain-groq>=1.1.3",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.0",
    "langchain-openrouter>=0.2.8",
    "langchain-pinecone>=0.2.13",
    "langchain-qdrant>=1.1.0",
    "mteb>=1.12.5",
    "nltk>=3.10.3",
    "numpy==1.26.4",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "pillow>=10.2.0",
    "pinecone>=7.3.0",
    "pypdf>=6.16.1",
    "python-docx>=1.2.0",
    "pyyaml>=6.0.3",
    "rank-bm25==0.2.2",
    "scikit-learn==1.4.2",
    "scipy==1.11.4",
    "sentence-transformers==2.7.0",
    "tabulate>=0.10.0",
    "torch>=2.4.0",
    "torchvision>=0.19.0",
    "transformers>=4.41.0",
    "unstructured>=0.25.2",
]

[project.scripts]
encodingandembedding = "encodingandembedding:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
